name: macOSでxHE-AACにするだけ

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: '動画のURLを入力'
        required: true

jobs:
  download-encode-upload:
    runs-on: macos-14
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - name: 最初にCPUをチェック
        run: sysctl machdep.cpu.brand_string & sysctl -n hw.logicalcpu_max
      - name: 諸々をダウンロード
        run: wget https://gitlab.com/ecodis/exhale/-/archive/v1.2.1/exhale-v1.2.1.tar.gz & curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && brew install ffmpeg
      - name: ビルド等
        run: chmod a+rx /usr/local/bin/yt-dlp & tar xvf exhale-v1.2.1.tar.gz && cd exhale-v1.2.1 && make BUILD32=0 release && sudo cp -v bin/exhale /usr/local/bin
      - name: YouTube音声ダウンロード
        run: yt-dlp -f 251 ${{ github.event.inputs.video_url }} -o audio.webm
      - name: webmの音声をwavにしてxHE-AAC(最低ビットレート)化
        run: ffmpeg -i audio.webm audio.wav && exhale a audio.wav audio.m4a
      - name: Upload video as artifact
        uses: actions/upload-artifact@v2
        with:
          name: encoded-video
          path: audio.m4a
